title: OBSS - Old Bell School System
description: Sistema di gioco di ruolo completo e testato / Complete and tested RPG system
theme: minima
plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

markdown: kramdown
highlighter: rouge

header_pages:
  - index.md

# SEO
lang: it
author: buzzqw
